server:
  spring.url: ${SERVER_SPRING_URL:10.5.0.7:8095}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://10.5.0.6:5432/signature_status?currentSchema=public}
  liquibase:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://10.5.0.6:5432/signature_status?currentSchema=public}
  rabbitmq:
    host: ${CLOUD_AMQP_HOST:10.5.0.5}
    uri: ${CLOUDAMQP_URL:amqp://guest:guest@10.5.0.5}
springdoc:
  swagger-ui:
    server.list: ${SPRINGDOC_SWAGGER-UI_SERVER_LIST:http://10.5.0.7:8095/api/signature_status}