server:
  port: ${SERVER_PORT:8095}
  servlet.context-path: ${SERVER_CONTEXT-PATH:/api/signature-status}
  compression.enabled: true
  error.include-message: always
  spring.url: ${SERVER_SPRING_URL:localhost:8095}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:3210/signature_status?currentSchema=public}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driverClassName: org.postgresql.Driver
    driver: org.postgresql.Driver
    connection-from: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true
  liquibase:
    enabled: true
    default-schema: public
    liquibase-schema: public
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:3210/signature_status?currentSchema=public}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    change-log: db.changelog/db.changelog-master.yaml
  rabbitmq:
    host: ${CLOUD_AMQP_HOST:localhost}
    port: ${CLOUDAMQP_PORT:5267}
    username: ${CLOUDAMQP_USERNAME:guest}
    password: ${CLOUDAMQP_PASSWORD:guest}
    uri: ${CLOUDAMQP_URL:amqp://guest:guest@localhost}
    queue: ${CLOUDAMQP_QUEUE:NOTIFICATION_QUEUE}
  application.name: voting-challenge
  web:
    locale: pt_BR
    localeResolver: fixed
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
springdoc:
  override-with-generic-response: false
  api-docs:
    enabled: true
  swagger-ui:
    server.list: ${SPRINGDOC_SWAGGER-UI_SERVER_LIST}
    enabled: true
    doc-expansion: none
    operations-sorter: alpha
    tags-sorter: alpha
    filter: true
    path: /swagger-ui
    disable-swagger-default-url: true
    csrf.enabled: false
  default-produces-media-type: application/json
api:
  standard-error:
    trace: false
